### ISSUE TITLE
"$ git pull https://github.com/tianon/gosu" instead of binary

### ISSUE THREAD

**Issue by dkdndes** [2hamed/docker-pg-replication#1]
Like to suggest to add 

     $ git pull https://github.com/tianon/gosu  

in the docu, instead of binary within the repository.

**Comment by 2hamed** [comment]
Well the problem is that my internet connection was not stable at the time and I couldn't pull the gosu from github on build time, so I had put the binary file on-premise.
But you can go ahead and fork it and do it as you please.
