### ISSUE TITLE
Deploy master and slave on different machines

### ISSUE THREAD

**Issue by pai911** [2hamed/docker-pg-replication#4]
I am not very familiar with docker-compose

But this sample looks like running master & slave on the same machine.

If I am right, is there a way to run them on two different machines?

**Comment by 2hamed** [comment]
Since all containers are communicating through the docker underlying network, it doesn't matter which machine the slaves are running on. Using `Docker Swarm` you can deploy this configuration on as many nodes as you need.

**Comment by pai911** [comment]
That makes sense. Thank you very much! I'll close my question!

**Comment by Hasdik** [comment]
@2hamed, you can help deploy master and slave on different machines?
